# Generated by Django 5.1 on 2024-09-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_historicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
